const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  init: () => ipcRenderer.invoke('init'),
  addCustomer: (customer) => ipcRenderer.invoke('customer:add', customer),
  updateCustomer: (customer) => ipcRenderer.invoke('customer:update', customer),
  deleteCustomer: (id) => ipcRenderer.invoke('customer:delete', id),
  addProduct: (product) => ipcRenderer.invoke('product:add', product),
  updateProduct: (product) => ipcRenderer.invoke('product:update', product),
  deleteProduct: (id) => ipcRenderer.invoke('product:delete', id),
  createInvoiceAndSend: (payload) => ipcRenderer.invoke('invoice:createAndSend', payload),
  addSupplier: (supplier) => ipcRenderer.invoke('supplier:add', supplier),
  updateInvoice: (payload) => ipcRenderer.invoke('invoice:update', payload),
  getInvoicePayments: (invoiceId) => ipcRenderer.invoke('invoice:getPayments', invoiceId),
  getInvoiceLines: (invoiceId) => ipcRenderer.invoke('invoice:getLines', invoiceId),
  updateInvoicePayments: (payload) => ipcRenderer.invoke('invoice:updatePayments', payload),
  deleteInvoice: (id) => ipcRenderer.invoke('invoice:delete', id),
  updatePurchase: (payload) => ipcRenderer.invoke('purchase:update', payload),
  deletePurchase: (id) => ipcRenderer.invoke('purchase:delete', id),
  updateSupplier: (supplier) => ipcRenderer.invoke('supplier:update', supplier),
  deleteSupplier: (id) => ipcRenderer.invoke('supplier:delete', id),
  addPurchase: (purchase) => ipcRenderer.invoke('purchase:add', purchase),
  addPurchasePayment: (payment) => ipcRenderer.invoke('purchase:payment', payment),
  createInvoice: (invoice) => ipcRenderer.invoke('invoice:create', invoice),
  createSplitSale: (payload) => ipcRenderer.invoke('sale:createSplit', payload),
  addInvoicePayment: (payment) => ipcRenderer.invoke('invoice:payment', payment)
  ,
  getCompanies: () => ipcRenderer.invoke('company:getAll'),
  addCompany: (payload) => ipcRenderer.invoke('company:add', payload),
  updateCompany: (payload) => ipcRenderer.invoke('company:update', payload),
  deleteCompany: (id) => ipcRenderer.invoke('company:delete', id),
  getSetting: (key) => ipcRenderer.invoke('settings:get', key),
  setSetting: (key, value) => ipcRenderer.invoke('settings:set', key, value),
  getProductShares: (productId) => ipcRenderer.invoke('product:getShares', productId),
  setProductShares: (productId, shares) => ipcRenderer.invoke('product:setShares', productId, shares),
  getProductRoleShares: (productId) => ipcRenderer.invoke('product:getRoleShares', productId),
  setProductRoleShares: (productId, shares) => ipcRenderer.invoke('product:setRoleShares', productId, shares),
  getRoles: () => ipcRenderer.invoke('roles:getAll'),
  createByRole: (payload) => ipcRenderer.invoke('sale:createByRole', payload),
  getProductRoleCompanies: (productId) => ipcRenderer.invoke('product:getRoleCompanies', productId),
  setProductRoleCompanies: (productId, entries) => ipcRenderer.invoke('product:setRoleCompanies', productId, entries),
  sendEmail: (payload) => ipcRenderer.invoke('email:send', payload)
  ,
  selectLogo: () => ipcRenderer.invoke('dialog:selectLogo')
  ,
  markUrssafDeclared: (payload) => ipcRenderer.invoke('urssaf:markDeclared', payload),
  addUrssafPayment: (payload) => ipcRenderer.invoke('urssaf:addPayment', payload),
  // Raw materials
  getRawMaterials: () => ipcRenderer.invoke('rawMaterial:getAll'),
  addRawMaterial: (material) => ipcRenderer.invoke('rawMaterial:add', material),
  updateRawMaterial: (material) => ipcRenderer.invoke('rawMaterial:update', material),
  deleteRawMaterial: (id) => ipcRenderer.invoke('rawMaterial:delete', id),
  getProductMaterials: (productId) => ipcRenderer.invoke('product:getMaterials', productId),
  setProductMaterials: (productId, materials) => ipcRenderer.invoke('product:setMaterials', productId, materials),
  calculateProductCost: (productId) => ipcRenderer.invoke('product:calculateCost', productId),
  addRawMaterialPurchase: (purchase) => ipcRenderer.invoke('rawMaterialPurchase:add', purchase),
  getRawMaterialPurchases: () => ipcRenderer.invoke('rawMaterialPurchase:getAll'),
  updateRawMaterialPurchase: (purchase) => ipcRenderer.invoke('rawMaterialPurchase:update', purchase),
  deleteRawMaterialPurchase: (id) => ipcRenderer.invoke('rawMaterialPurchase:delete', id)
});
